import { ActiveGameRuntime } from "../../engine/index.js";
import { FakeGameRenderer } from "../../engine/testing/fake-renderer.js";
import { createFakeGameServices } from "../../engine/testing/fake-services.js";
import { assert, type TestCase } from "../../test/harness.js";
import { SKY_RIDERS_AUDIO_IDS } from "./effects.js";
import { SKY_RIDERS_MODULE, SkyRidersGameInstance } from "./module.js";
class ThrowingRenderer extends FakeGameRenderer { public override clear():void{throw new Error("injected renderer failure");} }
export const tests:readonly TestCase[]=[
{name:"P12-010 real module consumes shared two-player input audio renderer and lifecycle calls",run:()=>{const services=createFakeGameServices(0x1200);const game=new SkyRidersGameInstance(services);game.start({players:2,difficulty:"squall",seed:0x1200});services.input.setHeld(1,"right",true);services.input.setHeld(1,"action-1",true);services.input.setHeld(2,"left",true);services.input.setHeld(2,"action-1",true);game.update(1/60);game.render(new FakeGameRenderer());assert(services.audio.playedEffects.filter(id=>id===SKY_RIDERS_AUDIO_IDS.flap).length===2,"both players must flap via shared input/audio");services.input.clearEdges();game.pause();game.update(1/60);assert(services.audio.playedEffects.filter(id=>id===SKY_RIDERS_AUDIO_IDS.flap).length===2,"pause must stop gameplay updates");game.resume();game.reset();game.render(new FakeGameRenderer());game.destroy();game.destroy();}},
{name:"P12-010 real Sky Riders update failure is isolated by production runtime",run:async()=>{const services=createFakeGameServices(0x1201);const errors:string[]=[];const runtime=new ActiveGameRuntime(services,e=>errors.push(e.phase));await runtime.load(SKY_RIDERS_MODULE);await runtime.start({players:1,difficulty:"squall",seed:0x1201});runtime.update(-1);assert(runtime.state==="error"&&runtime.activeGameId===null,"update failure must isolate game");assert(errors.includes("update")&&services.audio.stopAllCount>=1,"failure must report and clean audio");}},
{name:"P12-010 real Sky Riders render failure is isolated by production runtime",run:async()=>{const services=createFakeGameServices(0x1202);const errors:string[]=[];const runtime=new ActiveGameRuntime(services,e=>errors.push(e.phase));await runtime.load(SKY_RIDERS_MODULE);await runtime.start({players:1,difficulty:"breeze",seed:0x1202});runtime.render(new ThrowingRenderer());assert(runtime.state==="error"&&runtime.activeGameId===null,"render failure must isolate game");assert(errors.includes("render")&&services.audio.stopAllCount>=1,"render failure must report and clean");}},
];
