import { SeededRandomService } from "../../engine/testing/fake-services.js";
import { assert, type TestCase } from "../../test/harness.js";
import { SKY_RIDERS_RUN_RULES, SKY_RIDERS_SCORING, skyRidersEnemyCount } from "./design.js";
import { createSkyRider } from "./physics.js";
import { SkyRidersSimulation, type SkyRidersEnemyState, type SkyRidersPlayerState, type SkyRidersStormSeed } from "./simulation.js";
function playerState(player:1|2,x:number,y:number,lives=3):SkyRidersPlayerState{return Object.freeze({player,rider:createSkyRider(player,{x,y}),lives,active:true});}
function enemyState(id:number,x:number,y:number):SkyRidersEnemyState{return Object.freeze({rider:createSkyRider(id,{x,y}),decisionSeconds:1});}
export const tests: readonly TestCase[] = [
  {name:"P12-005 fixed seed reproduces enemy generation and AI decisions",run:()=>{const a=new SkyRidersSimulation({rng:new SeededRandomService(0x512),difficulty:"squall",players:1});const b=new SkyRidersSimulation({rng:new SeededRandomService(0x512),difficulty:"squall",players:1});for(let i=0;i<90;i+=1){a.update([],1/60);b.update([],1/60);}assert(JSON.stringify(a.enemies)===JSON.stringify(b.enemies),"same seed must reproduce AI");}},
  {name:"P12-006 higher player defeats enemy and creates one bounded storm seed",run:()=>{const s=new SkyRidersSimulation({rng:new SeededRandomService(1),difficulty:"breeze",players:1,initialPlayerStates:[playerState(1,160,100)],initialEnemies:[enemyState(100,160,110)]});const e=s.update([],0);assert(s.enemies.length===0&&s.stormSeeds.length===1&&s.score===100,"higher rider must defeat enemy");assert(e.some(x=>x.type==="enemy-defeated"),"defeat event required");}},
  {name:"P12-006 lower player loses one reserve and respawns with protection",run:()=>{const s=new SkyRidersSimulation({rng:new SeededRandomService(2),difficulty:"squall",players:1,initialPlayerStates:[playerState(1,160,112)],initialEnemies:[enemyState(100,160,100)]});s.update([],0);const p=s.players[0];assert(p?.lives===2&&p.active&&(p.rider.invulnerabilitySeconds>0),"lower player must lose reserve and respawn protected");}},
  {name:"P12-006 near-equal altitude resolves as a non-scoring separating clash",run:()=>{const s=new SkyRidersSimulation({rng:new SeededRandomService(3),difficulty:"squall",players:1,initialPlayerStates:[playerState(1,160,100)],initialEnemies:[enemyState(100,160,102)]});const e=s.update([],0);assert(s.enemies.length===1&&s.players[0]?.lives===3&&s.score===0,"tie must be non-scoring");assert(e.some(x=>x.type==="combat-clash"),"clash event required");}},
  {name:"P12-007 storm seed collection awards bonus and expiry reforms enemy",run:()=>{const seed:SkyRidersStormSeed=Object.freeze({id:1,position:Object.freeze({x:160,y:100}),velocityY:0,remainingSeconds:2});const collect=new SkyRidersSimulation({rng:new SeededRandomService(4),difficulty:"breeze",players:1,initialPlayerStates:[playerState(1,160,100)],initialEnemies:[enemyState(100,30,40)],initialStormSeeds:[seed]});collect.update([],0);assert(collect.stormSeeds.length===0&&collect.score===SKY_RIDERS_SCORING.recovery,"seed must collect");const exp=Object.freeze({id:1,position:Object.freeze({x:280,y:60}),velocityY:0,remainingSeconds:0.01});const reform=new SkyRidersSimulation({rng:new SeededRandomService(5),difficulty:"breeze",players:1,initialPlayerStates:[playerState(1,40,100)],initialEnemies:[],initialStormSeeds:[exp]});const ev=reform.update([],0.02);assert(reform.enemies.length===1&&ev.some(x=>x.type==="storm-seed-reformed"),"expired seed must reform enemy");}},
  {name:"P12-007 storm seed lands when gravity reverses its vertical motion during the crossing step",run:()=>{const seed:SkyRidersStormSeed=Object.freeze({id:1,position:Object.freeze({x:50,y:150}),velocityY:-1,remainingSeconds:5});const s=new SkyRidersSimulation({rng:new SeededRandomService(8),difficulty:"breeze",players:1,initialPlayerStates:[playerState(1,250,100)],initialEnemies:[enemyState(100,280,40)],initialStormSeeds:[seed]});s.update([],0.22);const landed=s.stormSeeds[0];assert(landed!==undefined,"seed must remain");assert(landed.position.y===158&&landed.velocityY===0,"gravity-reversed crossing must land on west ledge");}},
  {name:"P12-008 empty wave awards bonus advances and clamps population",run:()=>{const s=new SkyRidersSimulation({rng:new SeededRandomService(6),difficulty:"tempest",players:1,initialEnemies:[],initialStormSeeds:[],initialWave:20});const e=s.update([],0);assert(s.wave===21&&s.enemies.length===SKY_RIDERS_RUN_RULES.maxEnemies,"wave must advance and cap");assert(skyRidersEnemyCount("tempest",100)===SKY_RIDERS_RUN_RULES.maxEnemies,"helper must cap");assert(e.some(x=>x.type==="wave-cleared"),"wave event required");}},
  {name:"P12-009 two-player cooperative run ends only after both players exhaust reserves",run:()=>{const s=new SkyRidersSimulation({rng:new SeededRandomService(7),difficulty:"squall",players:2,initialPlayerStates:[playerState(1,80,112,1),playerState(2,240,112,1)],initialEnemies:[enemyState(100,80,100),enemyState(101,240,100)]});const e=s.update([],0);assert(s.gameOver&&s.players.every(p=>!p.active&&p.lives===0),"both players must be out");assert(e.filter(x=>x.type==="game-over").length===1&&s.update([],1).length===0,"terminal event must occur once");}},
];
