import { ActiveGameRuntime, type FrameCallback, type FrameScheduler, type GameRenderer, type GameRuntimeErrorEvent } from "../../engine/index.js";
import { createFakeGameServices } from "../../engine/testing/fake-services.js";
import { FakeGameRenderer } from "../../engine/testing/fake-renderer.js";
import { JUNGLE_QUEST_MODULE } from "../../games/jungle-quest/module.js";
import { assert, type TestCase } from "../../test/harness.js";
import { LoopingGameHost } from "./looping-game-host.js";
class SoakScheduler implements FrameScheduler { private nextHandle=1; private readonly callbacks=new Map<number,FrameCallback>(); public request(callback:FrameCallback):number{const h=this.nextHandle++;this.callbacks.set(h,callback);return h;} public cancel(handle:number):void{this.callbacks.delete(handle);} public get pendingCount():number{return this.callbacks.size;} }
class ThrowingRenderer extends FakeGameRenderer implements GameRenderer { public override clear():void{throw new Error("injected Jungle Quest render failure");} }
const OPTIONS=Object.freeze({players:1,difficulty:"expedition",seed:0x1313});
export const tests: readonly TestCase[]=[
 {name:"P13-010 forty-cycle real-module lifecycle soak retains one frame chain and no stale resources",run:async()=>{const scheduler=new SoakScheduler();const services=createFakeGameServices();const host=new LoopingGameHost(()=>services,undefined,scheduler);for(let cycle=0;cycle<40;cycle+=1){await host.launch(JUNGLE_QUEST_MODULE,{...OPTIONS,seed:cycle+1});assert(host.activeGameId==="jungle-quest"&&scheduler.pendingCount===1,"launch must own exactly one frame callback");services.input.setHeld(1,"action-1",true);await host.restart();assert(scheduler.pendingCount===1,"restart must preserve exactly one frame callback");assert(!services.input.isHeld(1,"action-1"),"restart must clear stale held input from prior run");host.exit();assert(host.activeGameId===null&&Number(scheduler.pendingCount)===0,"exit must release game and frame callback");assert(services.audio.activeCount===0,"exit must release audio");}}},
 {name:"P13-010 update-time failure releases Jungle Quest resources and is recoverable",run:async()=>{const services=createFakeGameServices();const failures:GameRuntimeErrorEvent[]=[];const runtime=new ActiveGameRuntime(services,(event)=>failures.push(event));await runtime.load(JUNGLE_QUEST_MODULE);await runtime.start(OPTIONS);services.input.isHeld=()=>{throw new Error("injected Jungle Quest input/update failure");};runtime.update(1/60);assert(runtime.state==="error"&&failures.some((event)=>event.phase==="update"),"update failure must enter error and report phase");assert(services.audio.activeCount===0&&services.audio.stopAllCount>=1,"failure must release audio ownership");runtime.recover();assert(String(runtime.state)==="unloaded","runtime must recover to unloaded");}},
 {name:"P13-010 render-time failure releases Jungle Quest resources and is recoverable",run:async()=>{const services=createFakeGameServices();const failures:GameRuntimeErrorEvent[]=[];const runtime=new ActiveGameRuntime(services,(event)=>failures.push(event));await runtime.load(JUNGLE_QUEST_MODULE);await runtime.start(OPTIONS);runtime.render(new ThrowingRenderer());assert(runtime.state==="error"&&failures.some((event)=>event.phase==="render"),"render failure must enter error and report phase");assert(services.audio.activeCount===0&&services.audio.stopAllCount>=1,"render failure must release audio ownership");runtime.recover();assert(String(runtime.state)==="unloaded","runtime must recover to unloaded");}},
];
