import { assert, type TestCase } from "../../test/harness.js";
import { JUNGLE_QUEST_SCORING } from "./design.js";
import { createJungleQuestPlayer, type JungleQuestPlayerState } from "./player.js";
import { JungleQuestSimulation } from "./simulation.js";
import { jungleQuestCollectibleIds } from "./world.js";
const N=Object.freeze({horizontal:0 as const,vertical:0 as const,jumpPressed:false,vinePressed:false});
function player(x:number,y:number):JungleQuestPlayerState{return createJungleQuestPlayer({x,y});}
export const tests: readonly TestCase[]=[
 {name:"P13-006 contact hazard costs one life and respawns with protection",run:()=>{const s=new JungleQuestSimulation({difficulty:"expedition",initialPlayer:player(220,182),initialScore:300});const events=s.update(N,0);assert(s.lives===2&&s.score===200,"hazard must cost one life and penalty");assert(events.some((e)=>e.type==="player-hit"),"hit must emit event");assert(s.roomId==="fern-gate"&&s.player.position.x===24&&s.invulnerabilitySeconds>0,"survivor must respawn at checkpoint with protection");s.update(N,.01);assert(Number(s.lives)===2,"protection must prevent immediate repeat contact loss");}},
 {name:"P13-006 pit fall costs a life and returns to checkpoint",run:()=>{const s=new JungleQuestSimulation({difficulty:"expedition",initialPlayer:player(275,260)});const events=s.update(N,0);assert(s.lives===2&&events.some((e)=>e.type==="player-hit"),"falling below room must cost one life");assert(s.player.position.x===24&&s.player.position.y===182,"pit must respawn at checkpoint");}},
 {name:"P13-006 pit recovery is immediate even during contact protection",run:()=>{const s=new JungleQuestSimulation({difficulty:"expedition",initialPlayer:player(275,260),initialInvulnerabilitySeconds:1});s.update(N,0);assert(s.lives===2&&s.player.position.y===182,"pit must bypass contact-only invulnerability");}},
 {name:"P13-006 room transition advances checkpoint and awards once",run:()=>{const s=new JungleQuestSimulation({difficulty:"expedition",initialRoomId:"echo-hollow",initialPlayer:player(326,182)});const events=s.update(N,0);assert(s.roomId==="root-vault","right boundary must enter Root Vault");assert(s.score===JUNGLE_QUEST_SCORING.checkpoint&&events.some((e)=>e.type==="checkpoint"),"new checkpoint must score once");}},
 {name:"P13-007 relic collection is unique and scores once",run:()=>{const s=new JungleQuestSimulation({difficulty:"expedition",initialPlayer:player(92,132)});s.update(N,0);assert(s.hasCollected("jade-seed")&&s.score===JUNGLE_QUEST_SCORING.relic,"touching relic must collect and score");s.update(N,0);assert(s.collectedCount===1&&Number(s.score)===JUNGLE_QUEST_SCORING.relic,"collected relic must not score twice");}},
 {name:"P13-007 complete relic set at shrine produces terminal score",run:()=>{const s=new JungleQuestSimulation({difficulty:"expedition",initialRoomId:"sun-shrine",initialPlayer:player(301,182),collectedIds:jungleQuestCollectibleIds(),initialScore:1000});const events=s.update(N,0);assert(s.ended&&s.endReason==="completed"&&s.score>1000,"finish with all relics must complete and award bonus");assert(events.filter((e)=>e.type==="run-ended").length===1,"completion must emit one terminal event");assert(s.update(N,1).length===0,"ended run must stop gameplay events");}},
 {name:"P13-007 timer expiration terminates run without bonus",run:()=>{const s=new JungleQuestSimulation({difficulty:"expedition",initialElapsedSeconds:164.99,initialScore:450});const events=s.update(N,.02);assert(s.ended&&s.endReason==="time-expired"&&s.score===450,"expired timer must preserve score and end run");assert(events.some((e)=>e.type==="run-ended"&&e.reason==="time-expired"),"timer must emit terminal event");}},
 {name:"P13-006 final life loss is terminal",run:()=>{const s=new JungleQuestSimulation({difficulty:"expedition",initialPlayer:player(220,182),initialLives:1});const events=s.update(N,0);assert(s.ended&&s.endReason==="out-of-lives"&&s.lives===0,"last hazard hit must end run");assert(events.some((e)=>e.type==="run-ended"&&e.reason==="out-of-lives"),"last life must emit terminal event");}},
];
